export type BLOCKQUOTE_INFO = '[!INFO]';

export type BLOCKQUOTE_WARNING = '[!WARNING]';

export type BLOCKQUOTE_ERROR = '[!ERROR]';

export type BLOCKQUOTE_SUCCESS = '[!SUCCESS]';

export type BLOCKQUOTE_LABEL = BLOCKQUOTE_INFO | BLOCKQUOTE_WARNING | BLOCKQUOTE_ERROR | BLOCKQUOTE_SUCCESS;
